### ISSUE TITLE
Error checking Typescript files due to lack of NODE.

### ISSUE THREAD

**Issue by claflico** [newtmitch/docker-sonar-scanner#9]
When using your image, the scan crashes with the following error whenever it tries to scan Typescript files:

ERROR: Failed to get Node.js version.No TypeScript files will be analyzed. You can exclude TypeScript files from analysis with 'sonar.exclusions' property

I was able to fix it by creating a custom image from your image and installing node. Not sure if that's something you might consider adding to this image.

**Comment by newtmitch** [comment]
Hey Cory - thanks for the note. Let me check this out this week and see if that's worth adding. My gut reaction says "yes". :)

**Comment by kaspirovski** [comment]
I have the same problem with analyzing TypeScript.

<pre>INFO: Sensor TypeScript Sensor [typescript]
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 15.517s
INFO: Final Memory: 19M/329M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Failed to run external process `node /root/src/.scannerwork/project/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner`. Run with -X for more information
ERROR: Caused by: Cannot run program "node": error=2, No such file or directory
ERROR: Caused by: error=2, No such file or directory
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
</pre>

**Comment by newtmitch** [comment]
Fixed. Sorry for the delay, everyone. RL / job takes precedence. :)
